# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         XML-Filter-Recorder
version:      1.00
version_from: lib/XML/Filter/Recorder.pm
installdirs:  site
requires:
    Test::More:                    0.47
    XML::SAX:                      0.12
    XML::SAX::EventMethodMaker:    0.1
    XML::SAX::Writer:              0.42

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
